In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
x_train = torch.FloatTensor([1,2,3]).unsqueeze(-1)
y_train = torch.FloatTensor([1,2,3]).unsqueeze(-1)

In [4]:
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)


In [5]:
optimizer = optim.SGD([W,b], lr=0.01)

In [6]:
nb_epochs = 1000
for epoch in range(1,nb_epochs+1):
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train)**2) #mse mean squared error
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    print("Epoch {:4d}/{} W: {:.3f}, Cost: {:.6f}".format(epoch,nb_epochs,W.item(), cost.item()))

Epoch    1/1000 W: 0.093, Cost: 4.666667
Epoch    2/1000 W: 0.176, Cost: 3.692741
Epoch    3/1000 W: 0.250, Cost: 2.922885
Epoch    4/1000 W: 0.316, Cost: 2.314337
Epoch    5/1000 W: 0.374, Cost: 1.833292
Epoch    6/1000 W: 0.426, Cost: 1.453034
Epoch    7/1000 W: 0.473, Cost: 1.152441
Epoch    8/1000 W: 0.514, Cost: 0.914819
Epoch    9/1000 W: 0.551, Cost: 0.726974
Epoch   10/1000 W: 0.583, Cost: 0.578474
Epoch   11/1000 W: 0.612, Cost: 0.461073
Epoch   12/1000 W: 0.638, Cost: 0.368257
Epoch   13/1000 W: 0.661, Cost: 0.294872
Epoch   14/1000 W: 0.682, Cost: 0.236847
Epoch   15/1000 W: 0.700, Cost: 0.190963
Epoch   16/1000 W: 0.716, Cost: 0.154676
Epoch   17/1000 W: 0.731, Cost: 0.125975
Epoch   18/1000 W: 0.744, Cost: 0.103271
Epoch   19/1000 W: 0.755, Cost: 0.085307
Epoch   20/1000 W: 0.766, Cost: 0.071090
Epoch   21/1000 W: 0.775, Cost: 0.059834
Epoch   22/1000 W: 0.783, Cost: 0.050920
Epoch   23/1000 W: 0.791, Cost: 0.043856
Epoch   24/1000 W: 0.797, Cost: 0.038255
Epoch   25/1000 

Epoch  336/1000 W: 0.928, Cost: 0.003885
Epoch  337/1000 W: 0.928, Cost: 0.003867
Epoch  338/1000 W: 0.928, Cost: 0.003848
Epoch  339/1000 W: 0.928, Cost: 0.003830
Epoch  340/1000 W: 0.928, Cost: 0.003811
Epoch  341/1000 W: 0.929, Cost: 0.003793
Epoch  342/1000 W: 0.929, Cost: 0.003775
Epoch  343/1000 W: 0.929, Cost: 0.003757
Epoch  344/1000 W: 0.929, Cost: 0.003739
Epoch  345/1000 W: 0.929, Cost: 0.003721
Epoch  346/1000 W: 0.929, Cost: 0.003703
Epoch  347/1000 W: 0.930, Cost: 0.003685
Epoch  348/1000 W: 0.930, Cost: 0.003667
Epoch  349/1000 W: 0.930, Cost: 0.003650
Epoch  350/1000 W: 0.930, Cost: 0.003632
Epoch  351/1000 W: 0.930, Cost: 0.003615
Epoch  352/1000 W: 0.931, Cost: 0.003597
Epoch  353/1000 W: 0.931, Cost: 0.003580
Epoch  354/1000 W: 0.931, Cost: 0.003563
Epoch  355/1000 W: 0.931, Cost: 0.003546
Epoch  356/1000 W: 0.931, Cost: 0.003529
Epoch  357/1000 W: 0.931, Cost: 0.003512
Epoch  358/1000 W: 0.932, Cost: 0.003495
Epoch  359/1000 W: 0.932, Cost: 0.003478
Epoch  360/1000 

Epoch  652/1000 W: 0.966, Cost: 0.000849
Epoch  653/1000 W: 0.966, Cost: 0.000845
Epoch  654/1000 W: 0.966, Cost: 0.000841
Epoch  655/1000 W: 0.966, Cost: 0.000837
Epoch  656/1000 W: 0.967, Cost: 0.000833
Epoch  657/1000 W: 0.967, Cost: 0.000829
Epoch  658/1000 W: 0.967, Cost: 0.000825
Epoch  659/1000 W: 0.967, Cost: 0.000821
Epoch  660/1000 W: 0.967, Cost: 0.000817
Epoch  661/1000 W: 0.967, Cost: 0.000813
Epoch  662/1000 W: 0.967, Cost: 0.000809
Epoch  663/1000 W: 0.967, Cost: 0.000805
Epoch  664/1000 W: 0.967, Cost: 0.000801
Epoch  665/1000 W: 0.967, Cost: 0.000797
Epoch  666/1000 W: 0.967, Cost: 0.000794
Epoch  667/1000 W: 0.967, Cost: 0.000790
Epoch  668/1000 W: 0.968, Cost: 0.000786
Epoch  669/1000 W: 0.968, Cost: 0.000782
Epoch  670/1000 W: 0.968, Cost: 0.000778
Epoch  671/1000 W: 0.968, Cost: 0.000775
Epoch  672/1000 W: 0.968, Cost: 0.000771
Epoch  673/1000 W: 0.968, Cost: 0.000767
Epoch  674/1000 W: 0.968, Cost: 0.000764
Epoch  675/1000 W: 0.968, Cost: 0.000760
Epoch  676/1000 

In [7]:
print(W,b)

tensor([0.9854], requires_grad=True) tensor([0.0332], requires_grad=True)


In [8]:
# 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

In [16]:
# Model
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)
# Data
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]]) # 3x5
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) # 1x5

# Model Initialize
model = MultivariateLinearRegressionModel()

# optimizer
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20

for epoch in range(nb_epochs+1):
    
    # H(x)
    prediction = model(x_train)
    
    # cost
    cost = F.mse_loss(prediction, y_train)
    
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # Log
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 21463.248047
Epoch    1/20 Cost: 6734.021973
Epoch    2/20 Cost: 2117.189941
Epoch    3/20 Cost: 670.055054
Epoch    4/20 Cost: 216.451523
Epoch    5/20 Cost: 74.268211
Epoch    6/20 Cost: 29.698200
Epoch    7/20 Cost: 15.724677
Epoch    8/20 Cost: 11.341596
Epoch    9/20 Cost: 9.964717
Epoch   10/20 Cost: 9.529989
Epoch   11/20 Cost: 9.390655
Epoch   12/20 Cost: 9.343915
Epoch   13/20 Cost: 9.326152
Epoch   14/20 Cost: 9.317472
Epoch   15/20 Cost: 9.311702
Epoch   16/20 Cost: 9.306769
Epoch   17/20 Cost: 9.302166
Epoch   18/20 Cost: 9.297644
Epoch   19/20 Cost: 9.293129
Epoch   20/20 Cost: 9.288643


In [15]:
[x for x in model.parameters()]

[Parameter containing:
 tensor([[-0.3250,  0.5198, -0.5575]], requires_grad=True),
 Parameter containing:
 tensor([0.4026], requires_grad=True)]

In [17]:
model(x_train)

tensor([[154.7848],
        [182.2029],
        [181.3930],
        [198.5351],
        [137.2593]], grad_fn=<AddmmBackward>)