In [2]:
import numpy as np
import torch

In [7]:

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1,2,3], [4,5,6]])
m3 = torch.FloatTensor([[1,2],[3,4],[5,6]])

print(m3)
print(m1.matmul(m2))
print(m1.matmul(m3))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 9., 12., 15.],
        [19., 26., 33.]])


RuntimeError: size mismatch, m1: [2 x 2], m2: [3 x 2] at /opt/conda/conda-bld/pytorch-cpu_1549626403278/work/aten/src/TH/generic/THTensorMath.cpp:940

In [12]:
ft = torch.Tensor([0, 1, 2])

print(ft)
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).unsqueeze(-1).shape)
print(ft.unsqueeze(0))

tensor([0., 1., 2.])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1, 1])
tensor([[0., 1., 2.]])
