In [65]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# For reproducibility
torch.manual_seed(1)

In [66]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [67]:
class BinaryClassifier(nn.Module):
    def __init__(self): # 신경망 레이어의 구성요소 정의
        super().__init__() # nn.Module.__init__()의 내용 상속
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,x): # 호출시 수행되는 연산 정의
        return self.sigmoid(self.linear(x))

In [68]:
# Data
x_data = [[1, 2], 
          [2, 3], 
          [3, 1], 
          [4, 3], 
          [5, 3], 
          [6, 2]] # mxd , 6x2
y_data = [[0], [0], [0], [1], [1], [1]] # 5x1

In [69]:
# model init
model = BinaryClassifier()

optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):
    
    hypothesis = model(x_train)
    
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/100 Cost: 0.539713 Accuracy 83.33%
Epoch   10/100 Cost: 0.614853 Accuracy 66.67%
Epoch   20/100 Cost: 0.441875 Accuracy 66.67%
Epoch   30/100 Cost: 0.373145 Accuracy 83.33%
Epoch   40/100 Cost: 0.316358 Accuracy 83.33%
Epoch   50/100 Cost: 0.266094 Accuracy 83.33%
Epoch   60/100 Cost: 0.220498 Accuracy 100.00%
Epoch   70/100 Cost: 0.182095 Accuracy 100.00%
Epoch   80/100 Cost: 0.157299 Accuracy 100.00%
Epoch   90/100 Cost: 0.144091 Accuracy 100.00%
Epoch  100/100 Cost: 0.134272 Accuracy 100.00%


# 만들어보기

In [70]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [71]:
W = torch.zeros((2,1),  requires_grad=True)
b = torch.zeros(1,  requires_grad=True)

In [72]:
hypothesis = 1/ (1 + torch.exp(-(x_train.matmul(W)) + b))

In [73]:
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [74]:
losses = -(y_train * torch.log(hypothesis) + 
           (1 - y_train) * torch.log(1 - hypothesis))
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

# Loading Real Data

In [85]:
import numpy as np

In [87]:
# Data
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train[0:5])
print(y_train[0:5])

tensor([[-0.2941,  0.4874,  0.1803, -0.2929,  0.0000,  0.0015, -0.5312, -0.0333],
        [-0.8824, -0.1457,  0.0820, -0.4141,  0.0000, -0.2072, -0.7669, -0.6667],
        [-0.0588,  0.8392,  0.0492,  0.0000,  0.0000, -0.3055, -0.4927, -0.6333],
        [-0.8824, -0.1055,  0.0820, -0.5354, -0.7778, -0.1624, -0.9240,  0.0000],
        [ 0.0000,  0.3769, -0.3443, -0.2929, -0.6028,  0.2846,  0.8873, -0.6000]])
tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.]])


In [89]:
# Model
class BinaryClassifier(nn.Module):
    def __init__(self): # 신경망 레이어의 구성요소 정의
        super().__init__() # nn.Module.__init__()의 내용 상속
        self.linear = nn.Linear(8,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,x): # 호출시 수행되는 연산 정의
        return self.sigmoid(self.linear(x))

In [90]:
# Model initialize
model = BinaryClassifier()

optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):
    
    hypothesis = model(x_train)
    
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/100 Cost: 0.712866 Accuracy 40.32%
Epoch   10/100 Cost: 0.563852 Accuracy 67.72%
Epoch   20/100 Cost: 0.532828 Accuracy 74.18%
Epoch   30/100 Cost: 0.514797 Accuracy 75.76%
Epoch   40/100 Cost: 0.503438 Accuracy 77.08%
Epoch   50/100 Cost: 0.495832 Accuracy 77.60%
Epoch   60/100 Cost: 0.490505 Accuracy 77.47%
Epoch   70/100 Cost: 0.486647 Accuracy 77.47%
Epoch   80/100 Cost: 0.483778 Accuracy 76.55%
Epoch   90/100 Cost: 0.481599 Accuracy 76.55%
Epoch  100/100 Cost: 0.479916 Accuracy 76.81%
